name: uni_links_web
description: A web implementation of the Uni Links platform interface.
version: 0.1.1
homepage: https://github.com/avioli/uni_links/tree/master/uni_links_web

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # uni_links_platform_interface: ^1.0.0
  uni_links_platform_interface:
    path: ../uni_links_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: ">=3.29.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: UniLinksPlugin
        fileName: 'uni_links_web.dart'
